# Generated by Django 5.2.7 on 2025-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticketreply_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Non-Technical', 'Non-Technical'), ('Functional', 'Functional')], default='Technical', max_length=20),
        ),
    ]
